---
  - name: Enable firewalld
    service:
      name: firewalld
      state: started
      enabled: true

  # - name: Ensure MySQL can pass the firewall
  #   firewalld:
  #     service: mysql
  #     state: enabled
  #     permanent: yes
  #     immediate: yes

  - name: Open port
    firewalld:
      zone: public
      port: '{{item}}'
      permanent: true
      state: enabled
    with_items:
      - 3306/tcp
      - 4567/tcp
      - 4568/tcp
      - 4444/tcp

  - name: Reload firewalld
    service:
      name: firewalld
      state: reloaded
      enabled: true